server:
  servlet:
    context-path: /spring-boot-base
  port: 8080

client:
  gen:
    test-base-url: http://localhost:8083

spring:
  datasource:
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: blog
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

restTemplate:
  timeout:
    connection: 4000
    socket: 4000
    read: 4000
  http-client-max:
    perroute: 200
    total: 200

springdoc:
  show-actuator: true